# aws-terraform - CI Build
# https://github.com/ArtiomL/aws-terraform
# Artiom Lichtenstein
# v1.0.1, 08/10/2019

sudo: required

env:
  global:
  - REPO="artioml/aws-terraform"
  - secure: "CZGgAiBIaBOySxT/toM10FAqPqgnmlJNj/dXtVnYsgjRV0AF/zxYysLGmO/S3f4iT5hy1ig2uKAHkNSDCTIBeaD56lV5Vx6XCxZly5+9NCj29zQ494+VKq60CNstSl+hiHAwa9kVwgcvC+a34FR3VN+rzyRpQ50CIqDYLdKaLHPYhjwn3HNBn7uxdDPE7oGSXEnwpouhD0ZIl26EeYM7XX7NyJBZi7jwIick5POK4Bdd7u8mGdh8PE9wNtv+6PQRQ9svOHBp4woKMVv16PP9SuvCOO6LgnCtUlNsR8Uh9AW2o72vmXc1HzuNYMN5WZuT1lvBWme8LtzwqU8gr7km8+7C4z1QpCvsZEBJnIe0b21iOnwAU2w0Ut9yLydbCG7X9Y2NfiM5k8h5YOogxGeNzb3lvBuPaa75mJGH+xEBgzvNqbk3hv5cpRlI1Bd7f2R6tiOCYI182XSzs9LZJr6fdCRdXVOu/KusJZkhumt2hODEeqkrN051AezChfRJ65b1ZrR3lL0ToM7/0l+jqJS5am4ugCROCG8yqHzNhk6l7q/G1G0VfHrka3G1CF0vcLEjgIfezx+sGqqP+XGsyqU287GRsuyflYZzH5IsnXfdzUkCv+9KFSpTZPS9K5BT9uAjkFcNz3HXZElICWdDAV+zXaalKYsWPpSeKJEd3+Pk3qw="
  - secure: "Va53fzi9EEkrUqvdNB0oD22yzDYhEHlds40NY5iIsP5cwJ+G6PNLTk07He3mKaL5UG5eusxDK03egWGym7meaI5ADjSjTPvs86PX6v8Nsh0T+cRSpSMfFLFB06ffw6UQxxd3YSEpyFpEmfomvZqyQ6RxjjN92j6H60xIle+1olsZsiHQ7jGaT7+038VAQ7LGtpVgWCkrbIGmrvRxc2xc4wcYjUQ+jYjJHk9dDGLKl5r2KqHAKtWls4R31LVvAWWKsu5mFbdadVjpy0Nc9YdggGku6VFsT2hnBXH0+k7bAJpM28rQeFV4bTToNaeLhvNzbzlu/KfwbrZpJm5UnzucYH2M7ByV5afQ0s99iY67mPvYM8tTtgex+aOCBd/6/8g9eLu2Mc1yftz7VjWx6cDKmG9Wr4EpeETSylC8KB0BnKZmPFtY2W36l9iMIXnzt3I1roAp+Er5sogfIC2N5ABz4WtQpHDwx7f/3LCoQ7F5rw8Xd56gV91wKQzDWa0QmcwNoTJlccCMDgZ+XhYBBGfeEo/Ab40dcxQZB4jVKqQcSajfisREvthl5YRmGlnnbOGmkLHX6WVA3JV25M21Ce7rl+5zV3UaPVhwO6QwnK8sPvX3J1d368pvS/eWDrsC8fFlvyRnx5m9qcqCTkvnkhDYdx5gMbw03D/WKPNgPSbNQRg="

services:
  - docker

before_script:
  - chmod +x test/run.sh

script:
  - docker build -t $REPO .
  - test/run.sh

after_success:
  - docker images
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u $DOCKER_USER -p $DOCKER_PASS;
    docker push $REPO;
    fi

notifications:
  slack:
    secure: "eGNZ1sdovsDOfQlYiw+qNbwN5tZ8weyWoSML0PeXQygqfKkFtPj9x8bZQx8vgf61OGuOMcvjt9jbKn36bLXYzbT/P2YwUnPb5F1prM+GaBFShjmHfRytQEMzmQny0ljGRKg1Cm0MI6ybkdoEfKMsqpMBcEJwLrnuQlBbZYO3ZGJyvBZghW2q9FlAVpSg4H94I2b/aPJ0X7FVeSAaVWkHK4XTn2K0P/l0oNxHYRenpmeD6HXTAajrEIFGkrCFINUXxZ6EYDIB1IcQqtYI279mHnC4RsqDq9lkQltvLcKt8PNjQVanz5h+j22XY4rm9Aqd3E30B++IFXgspIWQSKltAKil9+ZSaYp9QmpdjO2cG3F1ATEnu31jncmTxJ9POy0hzkqlwhXkSoDAouyFlwyLoaXn7l5DVx7pm9AERSzXxd6uYPuqHQGvRXE+9nCxz+5jIId7l1OlZiMddrFlUmFdERgDGl3sopyEZtMwSDg+mqxjWKD312IqvAJ0gkBOm9Rgvvc8vOHRQXfLCJAJa6JaqjbyWT3N/u9Hkq45WEn24RKeOvrUYqfro5pVhLw7h5Jyo3fDuzihKDuUAEKKcWxhZYiYUsG9DOrI71DhP/H480H95Zrmn6L3AO3pQLzyEA6yjfa6av0pmwd9tNRfj5MFBpeOWCSeQ/f7P6HY1oD+L2Q="
