# f5-terraform - CI Build
# https://github.com/ArtiomL/f5-terraform
# Artiom Lichtenstein
# v1.0.0, 31/08/2018

sudo: required

env:
  global:
  - REPO="artioml/f5-terraform"

services:
  - docker

before_script:
  - chmod +x test/run.sh

script:
  - docker build -t $REPO .
  - test/run.sh

after_success:
  - docker images
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then
    fi

notifications:
  slack:
    secure: "24MoL888jRa+b9+O61KGKBv2cgVOdQQBWq4LCiJr4wOALjWA0RAoZhbi0FCtopXSBdNxo73ve1OqhLgN6BAfQlPpcm6aTzJ2GP/Igb+cnn9auUPwJQTn7f4g1dCitMoy3jBi1aX9ntdGeOJpN/X/GPGdJau1q1T5rHn6Y+8Y7XXZRmWWSYi+hSzih4RtfmR4WAuESNSi+V9n2kRRYysVq4mbYVgzUx8pFM64rgtA+/HFqGkyDgJvjJxJeR8qfqTak/wdVLkXlR6kD0f7Cdiwi5AoGxHWXX35DCHmdXEJnUHtIF9Upar2rSwFB6TuWBQm61Kd6FgoApRFs+h2vz5saaVMHn6eLhXMWAu5B/g4Pzl62svXfjYbDLgiR1u5htv7rjx/1d1Kt3r/6ejxifEOJY8/NbQ4+iHxa5Hae4IyiK3chquV+Z34Mqjf488Du2NdQt2XMgJWULsBgYPF/ZanRdXIF7M57dDRfg7Wo0ujzcWyjTlwCcFpN8r6qBV10hJ9WT+PycYzDHHSql7Nejw7PwO+5XojpY9ZdLO4dSgGUqtceDCFBMLKNZDvvA9TJX1XeXxOEboRdo7HO8as8Sy7/cEnH0459oFKVXQTVFGc9kE7gVlflB1MpjqH8pI/CouIolsgLFUglEQyDV9tS0hQve9hlTlX2aSl3AiO0AhvyVU="
