# aws-terraform - CI Build
# https://github.com/ArtiomL/aws-terraform
# Artiom Lichtenstein
# v1.0.1, 08/10/2019

sudo: required

env:
  global:
  - REPO="artioml/aws-terraform"
  - secure: "CZGgAiBIaBOySxT/toM10FAqPqgnmlJNj/dXtVnYsgjRV0AF/zxYysLGmO/S3f4iT5hy1ig2uKAHkNSDCTIBeaD56lV5Vx6XCxZly5+9NCj29zQ494+VKq60CNstSl+hiHAwa9kVwgcvC+a34FR3VN+rzyRpQ50CIqDYLdKaLHPYhjwn3HNBn7uxdDPE7oGSXEnwpouhD0ZIl26EeYM7XX7NyJBZi7jwIick5POK4Bdd7u8mGdh8PE9wNtv+6PQRQ9svOHBp4woKMVv16PP9SuvCOO6LgnCtUlNsR8Uh9AW2o72vmXc1HzuNYMN5WZuT1lvBWme8LtzwqU8gr7km8+7C4z1QpCvsZEBJnIe0b21iOnwAU2w0Ut9yLydbCG7X9Y2NfiM5k8h5YOogxGeNzb3lvBuPaa75mJGH+xEBgzvNqbk3hv5cpRlI1Bd7f2R6tiOCYI182XSzs9LZJr6fdCRdXVOu/KusJZkhumt2hODEeqkrN051AezChfRJ65b1ZrR3lL0ToM7/0l+jqJS5am4ugCROCG8yqHzNhk6l7q/G1G0VfHrka3G1CF0vcLEjgIfezx+sGqqP+XGsyqU287GRsuyflYZzH5IsnXfdzUkCv+9KFSpTZPS9K5BT9uAjkFcNz3HXZElICWdDAV+zXaalKYsWPpSeKJEd3+Pk3qw="
  - secure: "KgzJLnvoYmiUNkbT57UHPK79vQXcnHxgc27n7VluxXkinL0AUIBYfC3l3AajwdNyrqneCMMGcuHHtjkDnz6OC1WIXU37wWCqIpOG3pv4bmOhKiErSNSGKjczDqZiB3MrOjTVE5g2yxv52qjQVUOV5sgJPLkdqPjRMt619afUI0ccC0ifI/uPmmR0ijOJwJTouW6X5L/277/5osxsvsFmZ3ZDjC+/lVgyMlCUPL5CNW4lTv5bXK/0VnMia08c4zYhTpnLP1KCD0/z+pyVbVjhdqQ/A8mEb0RreyFlrMN1WhzYefRrKa6FHgqeaH52NtHmr7YY20KuGJpXeDeiEEufBf7FzgYD0QQcxdhSTMK+9H5fwn6t+UCg8z/zBtqKnTF5KjqNCGAlfNX8LLfffQos33loz8YixebNfSKMbTuEUAJN4ZIOKshawFhc8pdV2Jx2JvGpRbC/lq/GRUXSivv1K6hpbeYjrdgEC2Z5Cb3CWMEnbvgqoRbYEtYmTMMQGESjyO5cdebHp2IE78kQNOjX2U7/bP1Kpyuv4wqNWW43tHL/OCC1gyKs6egQen3ecuD4eClwPcrREI5rBTn8bPgzs3B2w+cTHxQnjGXhZD66F3mam25PJRJB05NUJZjvfG/wThcZQT7WDjDaDYq8nyIco/03gdd+rmEpO6gwts4FNxY="

services:
  - docker

before_script:
  - chmod +x test/run.sh

script:
  - docker build -t $REPO .
  - test/run.sh

after_success:
  - docker images
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u $DOCKER_USER -p $DOCKER_PASS;
    docker push $REPO;
    fi

notifications:
  slack:
    secure: "eGNZ1sdovsDOfQlYiw+qNbwN5tZ8weyWoSML0PeXQygqfKkFtPj9x8bZQx8vgf61OGuOMcvjt9jbKn36bLXYzbT/P2YwUnPb5F1prM+GaBFShjmHfRytQEMzmQny0ljGRKg1Cm0MI6ybkdoEfKMsqpMBcEJwLrnuQlBbZYO3ZGJyvBZghW2q9FlAVpSg4H94I2b/aPJ0X7FVeSAaVWkHK4XTn2K0P/l0oNxHYRenpmeD6HXTAajrEIFGkrCFINUXxZ6EYDIB1IcQqtYI279mHnC4RsqDq9lkQltvLcKt8PNjQVanz5h+j22XY4rm9Aqd3E30B++IFXgspIWQSKltAKil9+ZSaYp9QmpdjO2cG3F1ATEnu31jncmTxJ9POy0hzkqlwhXkSoDAouyFlwyLoaXn7l5DVx7pm9AERSzXxd6uYPuqHQGvRXE+9nCxz+5jIId7l1OlZiMddrFlUmFdERgDGl3sopyEZtMwSDg+mqxjWKD312IqvAJ0gkBOm9Rgvvc8vOHRQXfLCJAJa6JaqjbyWT3N/u9Hkq45WEn24RKeOvrUYqfro5pVhLw7h5Jyo3fDuzihKDuUAEKKcWxhZYiYUsG9DOrI71DhP/H480H95Zrmn6L3AO3pQLzyEA6yjfa6av0pmwd9tNRfj5MFBpeOWCSeQ/f7P6HY1oD+L2Q="
