# f5-terraform - CI Build
# https://github.com/ArtiomL/f5-terraform
# Artiom Lichtenstein
# v1.0.0, 31/08/2018

sudo: required

env:
  global:
  - REPO="artioml/f5-terraform"

services:
  - docker

before_script:
  - chmod +x test/run.sh

script:
  - docker build -t $REPO .
  - test/run.sh

after_success:
  - docker images
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then
    fi

notifications:
  slack:
    secure: "aPZga+eJPuC5fo/+hqspiyWmF8pFaDWfZStygH1IK+KewvSswiiQOrJUgAT4ETMlD+5Tho17ahra+/pdrPohsFZDqrb0LYuczFOl6+Y1srbBc2CkasJ4xXZIvjmzOOB9AN/qkMwZfZiPq7Zd2Lbn6+FnI4nYC8qVnDFb0p8mdnli/R6HseUH3M2pU3vZQ58n7eTVq9FPWr+uE8DzvpzUizFUiCi1k0JFYKEkEFCZongn71Uc3d8A9im5RLwy8LKWvlgeRFZmmbzmQzVlx6I+E2Uc2/f3TxzkCwoW+1yaphsfcpu+KRGzNgnXkawvugjLBhFLJVegVoN4MWNeYsYPCqzKbaJoe7KygBTDXpqprtYG7ah8qEdKEUs5vtSVDJecqO9ZaFR/PVwKHgzikNG8/0cAQXnCE5qVGrRbp0Wv06+3g2qCGbaL+dJGLG1iJ0tKb3+AwkVFbpfy8fZI1/eo8q4Zr9S8DSl8Umdea7d2KZUP3wQ9MoY3FsYN7QcK5QEHoHt0sv2XUs9+3qBSC382u2RQlz1nJ2RSehQ9y3RBuvo4uI+Yspac7vk73XI4IxPiiYkts7dxnS4HLaHfG8qpd2dbQLhy7v8Qx/kY/LJ1gnf2YhmYIo1Sm3PRPFemI6i+Q6mRl5/aT5OxdJV7iCH0VqA910NRgNJE+SiqJPgNPro="
