# f5-terraform - CI Build
# https://github.com/ArtiomL/f5-terraform
# Artiom Lichtenstein
# v1.0.0, 31/08/2018

sudo: required

env:
  global:
  - REPO="artioml/f5-terraform"
  - secure: "kquLqwojKwYhQeItq9l/UZSut4T1HSvXaYiIMiz8nGPSRNdzlTleHurccG6sSomYoMc1rmwqzDHF/D8vwtNBwLY8i5jLLWGsfuZ2F4YBqminr59LV/mzGtUbGzlE/cHjXmZtY0MPZkOid+Nn2t5h/t/ittmHO3lFMEaUehWZXC0a8f8J0661WNRypSclh2AZEM4s7Ha9VLe/A9V6cjh8u+M+IygzwcGqOaOr7jPY8Zd9/B0q3xbZoeoiVJzT3SNku0iHuAOSft2S5taXxI8OIY+jHnLb3z3JPOrw3xbKpAwHMDFwsW+1U3Y9hcOpYL+460V/iToYaXo0+//UyCDn5hQXatTdjppTPdZtgfC4S5tYUOPDrx7EUEVWciHHGuAxlX6gbUcKMxAOzV4RJP0SRA+UXnJxcFRVU3kdt0rbARrimXSBjHHDKHa0lsY37CnKqGM6HURYp+aQxuv/dotlcuJhRo5t/a+bh1SSEWjmdRXC7ePxSFvxYWOhxDcwbKWQFjQXK0SpXTjnGbOD5Z6AkQg/vf7a15cG+PjgI1q62pd9tPW5uD0mQI+cpHj7jzQ1c6NaGX0Wyyn7Z+iZEBoOYeE3zj0upcA521bFO3O6C5/WpOI16GJMcQXXcYfAeAOKhBaFU1oZIPZa1Ni0MOrs0SQ6xMEsy/ozVrYliyvZi0g="
  - secure: "RNX94FX8JJ0FtfaE9uNG3GHGRzLtJRFh/2R+CrkPdRpuVEb61seceMO3LFagjUIW1GMCxBrLXvm/KrgjjllXmEJG65v36esJ2JtIz3UhPRn6bs4GnbmAqqZjdH7LA2Jnj/2HfumQewLFDgTdoYVTYajQB690g2vOWy6PaioOC+EjZdUy6yq/eSh4l/BDXkrPH7nLFiju+26OrA7RBD9XZsGvvj/hAWTwF8pQwkpFGc1JnTBIPqN8+Or6SYAn6oyZJdxi+526xXd3eNwNE8fbUem4H0bXa2nv4CZYC8FPfR0vb0lvq4xDIDxIoZtEFPC/C/4z6blTPC3AHJLJ2Hcs9/oEDYHifXSH+KHrym/D75Ym3Lv4ghfQVDuksPPu7upYxfD9ZzXOFgXHI4pWsyJKWK5ZtG8UXgHYITEaDDIG8hcel3dXOTgEyaMfv2j+TKbn4kTbKAbm4O/p8zS4uLDYBPoWw263eiE1TPmQfoKMM9rB2OQMM2kgLzmtxZxte3wgaZK6TbFn3cbbZ3hk8jtk9e6VL/EZhZCVvWsLfu4Ncf/FwK2yEzhu5i6C71NYC33x/i5W3u/7BColhm0IH5w0AXLvFb3SmY6HlAcAdhEW2BMhR5SWl4p0kdw9+ARF0Chvf27DyC+QlCnZ4gi6llghDuIyPj/yYviNNOvepBujE90="

services:
  - docker

before_script:
  - chmod +x test/run.sh

script:
  - docker build -t $REPO .
  - test/run.sh

after_success:
  - docker images
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u $DOCKER_USER -p $DOCKER_PASS;
    docker push $REPO;
    fi

notifications:
  slack:
    secure: "U4CASbT57Te6Y3jdyTCuM7CLssKrLiot/p/jvTEN8TdCHsHdplA5puWQmRakZ5ijkKcvEM0JPv4wOUT3163vb5sPtSiSAN/8zrsbvCDmdqruigtRsC414dOVfkAT7UG7OUVmB817aqvip2wa+1JQCOnFhn53O/FWXIGPG6m5PvGebW8C0wDBqIR+KtRme7nmlPoXdEAIXV4VyVaVop2CK2BoGMsVk5lLBZv415iFzlAOeFCL2pXel5+ZWKNrYfq/G1zEfpUz6QMq6vmvT/slMHFKyksAKvwND8OM44Th70szW+r7ABW7D06fROPgl+AmFJ396I8EgmtJWDiCDRZgCSpUCldRzqiWHpAfVHPb5GHOsOlfv68C/SzGizClcWKcLuPpZhYjEjvtCNW/xz0Ab8cdidr9QDR0S7YzwVkkWlPobaSwgpb1vn9nNQpBKhhyET58RhQeXT5oaU496kV9UB937WyWAoGWEj6Z4knCZ1V5CkDEHoAiaPMDsGDAWV2EVLMVdrrnFCm/fhlYwcYDUAgH9HDgO11qcEsG2FAHi/uLegomViOhs8jqoDxwXfrHCnktpelb5MnBfhkmOhqxz4PyqUFrKso90FWg/AixJmo2IplptuW1AnFx7uRuCdUqJp0evXB+xD93ix8cfKAC9SuDa0GwgsnDT6nM6VlKCYg="
